package zy.nav.plugin

class ScanSetting {

    static final String PLUGIN_NAME = "zy.nav"

    /**
     * The register code is generated into this class
     */
    String generateToClassName = ''

    /**
     * you know. this is the class file(or entry in jar file) name
     */
    String generateToClassFileName = ''

    /**
     * The register code is generated into this method
     */
    static final String GENERATE_TO_METHOD_NAME = '<clinit>'

    /**
     * The package name of the class generated by the annotationProcessor
     */
    String scanPackageName = ''

    /**
     * register method name in class generateToClass
     */
    static final String REGISTER_METHOD_NAME = 'register'

    /**
     * scan for classes which implements this interface
     */
    String interfaceName = ''

    /**
     * scan result for {@link #interfaceName}
     * class names in this list
     */
    Set<String> classList = new LinkedHashSet<>()

    /**
     * constructor for arouter-auto-register settings
     * @param interfaceName interface to scan
     */
    ScanSetting(String generateToClassName, String scanPackageName, String interfaceName) {
        this.generateToClassName = generateToClassName
        this.generateToClassFileName = "${generateToClassName}.class"
        this.scanPackageName = scanPackageName
        this.interfaceName = interfaceName
    }

}